sources:
    - name: dlt_ingestion
      database: dev 
      schema: bronze 
      tables:
        - name: listings
          identifier: bronze_listings
        - name: bookings
          identifier: bronze_bookings
        - name: hosts
          identifier: bronze_hosts